#20 - February release notes
artipie/blog.artipie.com pull request #21
Opened 2021-02-26 11:32 UTC by olenagerasimova

Closes #20

2021-02-26 11:32 UTC, olenagerasimova commented
@g4s8 @genryxy please take a look, do we have smth to add?

2021-02-26 11:47 UTC, genryxy commented
@olenagerasimova probably this [one](https://github.com/artipie/npm-adapter/pull/189). Unpublish single version in Npm.
This [issue](https://github.com/artipie/helm-adapter/issues/96) was also resolved but I'm not sure if it should be mentioned.
This [changes](https://github.com/artipie/artipie/issues/851) although refer to build lifecycle. This [page](https://github.com/artipie/artipie/wiki/Build-lifecycle) was added to clarify used tools

2021-02-26 11:50 UTC, genryxy requested changes
@olenagerasimova thanks, see two minor comments

2021-02-26 11:50 UTC, genryxy commented on _posts/2021/02/2021-01-28-release-notes.md
> +Docker-adapter support granular permissions, which means that some operations can be granted for
@olenagerasimova should be `supports`

2021-02-26 11:50 UTC, genryxy commented on _posts/2021/02/2021-01-28-release-notes.md
> +the registry level operations or "repository". `Name` is the access recourse name, `action` can be
@olenagerasimova typo in the word `resource`

2021-02-26 12:10 UTC, olenagerasimova commented
@genryxy thanks, corrected

2021-02-26 12:19 UTC, olenagerasimova commented
@genryxy also thanks for the additions, I've added about npm unpublish, other changes seem too internal to be mentioned.

2021-02-26 12:33 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good to me

2021-03-04 07:54 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-03-04 07:57 UTC, merged