June blog post
artipie/blog.artipie.com pull request #24
Opened 2022-06-24 08:32 UTC by olenagerasimova

DO NOT MERGE! We have not released Artipie 0.24.0 yet

2022-06-24 08:42 UTC, dgarus requested changes
@olenagerasimova look at my comment, please

2022-06-24 08:42 UTC, dgarus commented on _posts/2021/02/2021-01-28-release-notes.md
> +recursively along with the removed file. This change fixed co16ected
16 -> nn

2022-06-24 16:57 UTC, loic-sharma commented on _posts/2022/06/2022-06-24-release-notes.md
> +Hello, it's been a while since the last Artipie blog post. Dispute of the absence of the posts,
Dispute should be despite:

```suggestion
Hello, it's been a while since the last Artipie blog post. Despite of the absence of the posts, 
```

2022-06-27 09:51 UTC, olenagerasimova commented
@dgarus corrected typos and added phase about docker image and release jar.

2022-06-27 09:56 UTC, dgarus approved these changes
Thanks!

2022-06-27 09:58 UTC, merged