August 2020 release notes
artipie/blog.artipie.com pull request #4
Opened 2020-08-31 18:22 UTC by olenagerasimova

I've tried to add blog post about key features implemented in August.

2020-09-01 07:53 UTC, olenagerasimova commented
@g4s8 @olegmoz please review

2020-09-01 14:32 UTC, g4s8 requested changes
@olenagerasimova please check my comment

2020-09-01 14:32 UTC, g4s8 commented on _posts/2020/08/2020-08-13-release-notes.md
> +- artifacts validation on upload
@olenagerasimova maybe we can add links to the tickets here?

2020-09-02 08:12 UTC, yegor256 commented
@g4s8 @olegmoz looks good to me

2020-09-02 18:45 UTC, olenagerasimova commented
@g4s8 thanks, I've added links

2020-09-03 08:23 UTC, g4s8 reviewed
@olenagerasimova thanks

2020-09-03 08:23 UTC, g4s8 approved these changes

2020-09-03 08:24 UTC, merged

2020-09-03 14:00 UTC, olegmoz commented
@yegor256 it seems that https://blog.artipie.com/ does not show this post after merge, could you please look into it?

2020-09-03 14:26 UTC, yegor256 commented
@olenagerasimova @olegmoz it's published. See the changes I've made in 85985a9 We can't use `jekyll-bits` plugin, because GitHub publishes Jekyll sites in "safe" mode: https://jekyllrb.com/docs/github-pages/

2020-09-03 14:32 UTC, olegmoz commented
@yegor256 thank you!