#5 - september release notes
artipie/blog.artipie.com pull request #6
Opened 2020-09-30 15:35 UTC by olenagerasimova

Closes #5 
I've added blog post for September release notes.

@olegmoz could you, please, help me to gather info? I have the following questions:
- what has been done in the adapters? I am working on maven-proxy, you are merging npm and npm-proxy repositories, what else?
- as far as I remember Pavel worked on benchmarks, I'm thinks to add some links to this blog post. Could you please share some links?

2020-09-30 16:11 UTC, olegmoz commented
Here is list of all PRs merged this month, you can look through them to see if what was done in adapters, but I think that was mostly dependency fixes, CI fixes etc:
```
 - One more javadoc fix: https://github.com/artipie/rpm-adapter/pull/367
 - Javadoc fix: https://github.com/artipie/rpm-adapter/pull/365
 - Updated dependencies: https://github.com/artipie/rpm-adapter/pull/364
 - For #317: Added StorageHasRepoMd matcher: https://github.com/artipie/rpm-adapter/pull/343
 - Updated http to 0.16.1: https://github.com/artipie/go-adapter/pull/71
 - #62 - test for authorization: https://github.com/artipie/go-adapter/pull/68
 - #62 - Authorization added: https://github.com/artipie/go-adapter/pull/64
 - Pom clean up: https://github.com/artipie/go-adapter/pull/63
 - Update http version to 0.15.7: https://github.com/artipie/go-adapter/pull/59
 - #123 - Moved proxy docs to root README.md with some modifications: https://github.com/artipie/npm-adapter/pull/130
 - #123 - Moved proxy code to root: https://github.com/artipie/npm-adapter/pull/128
 - #122 - Fixed & refactored NpmCommandsTest: https://github.com/artipie/npm-adapter/pull/126
 - #124 - Removed codecov upload phase from maven.yml: https://github.com/artipie/npm-adapter/pull/125
 - #120 - Removed base path usage for routing: https://github.com/artipie/npm-adapter/pull/121
 - Bump dependencies: https://github.com/artipie/npm-adapter/pull/118
 - Atomicity check: https://github.com/artipie/asto/pull/283
 - Revert signature changes made with BlockingStorage: https://github.com/artipie/asto/pull/280
 - Back to vertx: https://github.com/artipie/asto/pull/279
 - #260 - Handle concurrently deleted proposals in StorageLock: https://github.com/artipie/asto/pull/264
 - #261 - extend TestResource: https://github.com/artipie/asto/pull/263
 - #260 - Throwing ValueNotFoundException when value absent in storage: https://github.com/artipie/asto/pull/262
 - #237 - Proper handling of errors in Storage.exclusively implementations: https://github.com/artipie/asto/pull/255
 - Updated deps: https://github.com/artipie/asto/pull/254
 - #237 - Storages exclusively method implementation: https://github.com/artipie/asto/pull/252
 - #237 - Replaced Storage.transaction with Storage.exclusively: https://github.com/artipie/asto/pull/250
 - #573 - Document user groups: https://github.com/artipie/artipie/pull/645
 - #573 - add groups to GetPermissionSlice: https://github.com/artipie/artipie/pull/644
 - #570 - Added documentation for repo on own port feature: https://github.com/artipie/artipie/pull/643
 - #573 - update http: https://github.com/artipie/artipie/pull/641
 - #603 - Verify curl request with authentication : https://github.com/artipie/artipie/pull/639
 - #637 - Configurable log level in MeasuredStorage, finest by default: https://github.com/artipie/artipie/pull/638
 - Bump asto version: https://github.com/artipie/artipie/pull/631
 - #603 - Check PUT and GET with auth disabled: https://github.com/artipie/artipie/pull/630
 - #570 - No repo name prefix on repository ports: https://github.com/artipie/artipie/pull/629
 - #572 - add reader group and permission: https://github.com/artipie/artipie/pull/627
 - #572 - Update adapters and docs: https://github.com/artipie/artipie/pull/626
 - #570 - Extracted BaseSlice, MainSlice and AllRepositoriesSlice: https://github.com/artipie/artipie/pull/625
 - #570 - Listen on repository ports: https://github.com/artipie/artipie/pull/623
 - #572 - read and save groups in AddUpdateUserSlice: https://github.com/artipie/artipie/pull/621
 - #572 - return groups in GetUserSlice: https://github.com/artipie/artipie/pull/620
 - #616 - Simplify user() method: https://github.com/artipie/artipie/pull/619
 - #571 - Added docs for path patterns support & fixed GET endpoint: https://github.com/artipie/artipie/pull/618
 - #572 - read/write groups in Users.FromStorageYaml: https://github.com/artipie/artipie/pull/617
 - #571 - Validating path patterns on update: https://github.com/artipie/artipie/pull/615
 - #601 - updated go-adapter: https://github.com/artipie/artipie/pull/613
 - #572 - read groups in AuthFromYaml: https://github.com/artipie/artipie/pull/612
 - #571 - PathPattern introduced: https://github.com/artipie/artipie/pull/611
 - #571 - Reading include patterns support in GetPermissionSlice: https://github.com/artipie/artipie/pull/610
 - #571 - Support for include-patterns in AddUpdatePermissionSlice: https://github.com/artipie/artipie/pull/600
 - #571 - Added included path patterns support to RepoPermissions.update: https://github.com/artipie/artipie/pull/598
 - Changed wrong urls.: https://github.com/artipie/white-paper/pull/30
 - Update http to 0.16.2: https://github.com/artipie/docker-adapter/pull/337
 - Updated http to 0.16.1: https://github.com/artipie/docker-adapter/pull/336
 - #296 - Add InvalidManifestException: https://github.com/artipie/docker-adapter/pull/329
 - #244 - work with Authentication.User instead of username: https://github.com/artipie/http/pull/245
 - #241 - User groups: https://github.com/artipie/http/pull/242
 - #238 - added `Action` to `Permission.ByName`: https://github.com/artipie/http/pull/240
 - #238 - created `Action` interface and its implementation: https://github.com/artipie/http/pull/239
 - #236 - Pom cleanup, upgraded ppom to 0.4: https://github.com/artipie/http/pull/237
 - #197 - fixed and tested RepoHead and MavenProxySlice: https://github.com/artipie/maven-adapter/pull/202
 - #197 - proxy central test: https://github.com/artipie/maven-adapter/pull/198
 - Update http to 0.16.1: https://github.com/artipie/maven-adapter/pull/196
 - #191 - Fixed invalid XML to comply with XCOP check: https://github.com/artipie/maven-adapter/pull/192
 - #189 - Extended locking scope in UpdateMavenSlice: https://github.com/artipie/maven-adapter/pull/190
 - #168 - updated asto: https://github.com/artipie/maven-adapter/pull/184
 - #137 - added tests with auth and deploy: https://github.com/artipie/maven-adapter/pull/182
 - #137 - initial it case for maven: https://github.com/artipie/maven-adapter/pull/180
 - #178 - Using exclusive storage access on metadata copy: https://github.com/artipie/maven-adapter/pull/179
 - #143 - remove code duplications from AstoValidUploadTest: https://github.com/artipie/maven-adapter/pull/177
 - #1 - Bumped HTTP dependency: https://github.com/artipie/nuget-adapter/pull/116
 - #113 - Repository.add access storage exclusively: https://github.com/artipie/nuget-adapter/pull/115
 - #113 - Repository accepts async Storage: https://github.com/artipie/nuget-adapter/pull/114
 - Updated http to 0.16.1: https://github.com/artipie/pypi-adapter/pull/125
 - #64 - Removed base path support: https://github.com/artipie/composer-adapter/pull/65
 - #1 - Bumped dependencies: https://github.com/artipie/composer-adapter/pull/57
 - Enable logs for tests: https://github.com/artipie/gem-adapter/pull/80
 - Bumped http and ppom: https://github.com/artipie/gem-adapter/pull/75
 - Bumped http, asto and ppom: https://github.com/artipie/gem-adapter/pull/74
 - #45 - dependencyManagement updated: https://github.com/artipie/ppom/pull/46
 - #1 - Added olegmoz & olenagerasimova to list of architect: https://github.com/artipie/ppom/pull/42
 - Updated ppom and http: https://github.com/artipie/files-adapter/pull/35
 - Delete api: https://github.com/artipie/files-adapter/pull/21
 - Bumped ppom, http and asto: https://github.com/artipie/helm-adapter/pull/71
 - Helm compatibility test: https://github.com/artipie/helm-adapter/pull/56
 - Script for benchmarks on specific versions of artipie: https://github.com/artipie/benchmarks/pull/29
 - Benchmarks reliability improvements: https://github.com/artipie/benchmarks/pull/28
 - #50 - Added Authenticator and Authenticator.Basic: https://github.com/artipie/http-client/pull/53
 - IT case with client slices and vertx: https://github.com/artipie/http-client/pull/49
 - #1 - Bumped dependencies: https://github.com/artipie/http-client/pull/48
 - August 2020 release notes [...]

2020-10-01 05:50 UTC, olenagerasimova commented
@olegmoz thanks, I've extended the list, please, review. Although, I think we should release artipie first, add release link here second and then publish this note.

2020-10-01 07:12 UTC, olegmoz requested changes
@olenagerasimova thanks for collecting all the info and putting it together, please see some comments

2020-10-01 07:12 UTC, olegmoz commented on _posts/2020/09/2020-09-30-release-notes.md
> +- list repository items
@olenagerasimova to me it seems that grammar is a little bit off here. It reads like "... allows create, manage, ...". I think we need to add "to" after allows, so it will be "... allows to: create, manage, ..."

2020-10-01 07:12 UTC, olegmoz commented on _posts/2020/09/2020-09-30-release-notes.md
> +repository permissions can be granted to the group, not individual users. [Readers group](https://github.com/artipie/artipie/issues/572)
@olenagerasimova I am not sure we should use "the" with "groups" or "group". Also "not individual users" part sounds like we cannot grant permissions to individual users anymore. I'd change it to "users can be added to multiple groups and repository permissions can be granted to a group, not to individual users only". Not sure about it though, maybe the phrase now is totally fine

2020-10-01 07:12 UTC, olegmoz commented on _posts/2020/09/2020-09-30-release-notes.md
> +- we added visualisation to our [benchmarks](https://artipie.github.io/artipie/benchmarks/index.html)
@olenagerasimova "Files adapter now" and "[Maven proxy]" items are capitalized while others are not

2020-10-01 07:12 UTC, olegmoz commented on _posts/2020/09/2020-09-30-release-notes.md
> +- we added visualisation to our [benchmarks](https://artipie.github.io/artipie/benchmarks/index.html)
@olenagerasimova it is not just visualization, the benchmark suite now runs for multiple versions at once, so they can be compared. Plus there is visualization for comparison. We may repharse it to something like "we improved our benchmarks to compare performance of multiple Artipie versions"

2020-10-01 07:14 UTC, olegmoz commented
@olenagerasimova also I am going to create a release `0.11` for Artipie, it's about time: https://github.com/artipie/artipie/issues/614#issuecomment-701938425

2020-10-01 08:30 UTC, olenagerasimova commented
@olegmoz thanks, all corrected

2020-10-01 08:40 UTC, olegmoz commented
@olenagerasimova thanks. Yes, lets wait for Maven update. Also I'd wait for release to happen before publishing the release notes

2020-10-01 08:40 UTC, olegmoz approved these changes

2020-10-02 08:42 UTC, olegmoz requested changes
@olenagerasimova please see one comment

2020-10-02 08:42 UTC, olegmoz commented on _posts/2020/09/2020-09-30-release-notes.md
> +  version 0.11, released just a few days ago.
@olenagerasimova `0.11` was released, just now and is available on DockerHub: https://hub.docker.com/layers/artipie/artipie/0.11/images/sha256-d8f20f938c4ee2e3a0f4bd956538495ae48641bd0ae9a6974be469db4f16934a?context=explore

So we are ready to publish, I'd suggest to update `date` and remove "released just a few days ago" part

2020-10-02 09:53 UTC, olenagerasimova commented
@olegmoz thanks, corrected dates and added link to release

2020-10-02 09:58 UTC, olegmoz approved these changes
@olenagerasimova thanks!

2020-10-02 09:58 UTC, merged